// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ProductInput struct {
	CategoryID     string  `json:"categoryID"`
	Name           string  `json:"name"`
	Price          int     `json:"price"`
	Brand          *string `json:"brand"`
	Description    *string `json:"description"`
	SellerUsername string  `json:"sellerUsername"`
}

type UserInput struct {
	Username    string `json:"username"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}
